let datasetId, plan;
const $ = (selector) => document.querySelector(selector);
const addText = (parent, tag, value) => { const element = document.createElement(tag); element.textContent = String(value ?? ''); parent.append(element); return element; };
function status(message, error = false) { $('#status').textContent = message; $('#status').className = error ? 'error' : ''; }
async function request(url, options = {}) { const response = await fetch(url, options); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.detail || 'Request failed'); return body; }

const understandButton = document.createElement('button'); understandButton.id = 'understand'; understandButton.className = 'secondary'; understandButton.type = 'button'; understandButton.textContent = 'Understand this dataset'; $('#profileCard .section-heading').append(understandButton);
const contextCard = document.createElement('section'); contextCard.id = 'contextCard'; contextCard.className = 'card hidden'; $('#profileCard').after(contextCard);

function showProfile(profile) {
  $('#profileCard').classList.remove('hidden'); $('#analysisCard').classList.remove('hidden');
  const summary = $('#summary'); summary.replaceChildren(); [['rows', profile.rows.toLocaleString()], ['columns', profile.columns], ['duplicate rows', profile.duplicate_rows]].forEach(([label, value]) => { const item = document.createElement('span'); addText(item, 'strong', value); item.append(` ${label}`); summary.append(item); });
  const columns = $('#columns'); columns.replaceChildren(); profile.column_profiles.forEach(column => { const item = document.createElement('article'); addText(item, 'b', column.name); const zeroInfo = column.zero_count ? ` · ${column.zero_count} zero (${column.zero_percentage}%)` : ''; addText(item, 'span', `${column.data_type} · ${column.missing_count} missing${zeroInfo} · ${column.unique_count} unique${column.potential_pii ? ' · PII-sensitive' : ''}`); columns.append(item); });
  $('#download').href = `/api/datasets/${encodeURIComponent(datasetId)}/download`;
}
function renderContext(context) {
  contextCard.replaceChildren(); contextCard.classList.remove('hidden'); const heading = document.createElement('div'); heading.className = 'section-heading'; const copy = document.createElement('div'); addText(copy, 'p', 'DATASET ORIENTATION').className = 'kicker'; addText(copy, 'h2', 'What this dataset can tell you'); heading.append(copy); contextCard.append(heading);
  addText(contextCard, 'p', context.dataset_description); addText(contextCard, 'p', `Likely row grain: ${context.likely_grain}`).className = 'helper';
  if (context.key_entities.length) { addText(contextCard, 'h3', 'Key entities'); addText(contextCard, 'p', context.key_entities.join(', ')); }
  addText(contextCard, 'h3', 'Field guide'); const fields = document.createElement('div'); fields.className = 'column-grid'; Object.entries(context.column_explanations).forEach(([name, explanation]) => { const field = document.createElement('article'); addText(field, 'b', name); addText(field, 'span', explanation); fields.append(field); }); contextCard.append(fields);
  if (context.caveats.length) { addText(contextCard, 'h3', 'Interpretation notes'); const caveats = document.createElement('ul'); context.caveats.forEach(note => addText(caveats, 'li', note)); contextCard.append(caveats); }
  addText(contextCard, 'h3', 'Suggested first questions'); const questions = document.createElement('div'); questions.className = 'suggestion-list'; context.suggested_questions.forEach(question => { const button = document.createElement('button'); button.className = 'secondary'; button.type = 'button'; button.textContent = question; button.addEventListener('click', () => { $('#question').value = question; $('#question').focus(); }); questions.append(button); }); contextCard.append(questions);
}
function renderPlan(nextPlan) {
  $('#planCard').classList.remove('hidden'); $('#risks').textContent = nextPlan.risks.join(' '); const suggestions = $('#suggestions'); suggestions.replaceChildren(); const all = [...nextPlan.suggestions, ...nextPlan.missing_value_suggestions]; if (!all.length) { addText(suggestions, 'p', 'No changes are recommended.'); return; }
  all.forEach(suggestion => { const label = document.createElement('label'); const checkbox = document.createElement('input'); checkbox.type = 'checkbox'; checkbox.value = suggestion.id; label.append(checkbox, ' '); addText(label, 'b', suggestion.id); label.append(' — '); addText(label, 'span', suggestion.reason); label.append(' '); addText(label, 'small', `(${suggestion.confidence} confidence)`); suggestions.append(label); });
}
function renderResult(data) {
  $('#query').textContent = data.sql; const notes = $('#interpretationNotes'); notes.replaceChildren(); if (data.interpretation_notes?.length) { data.interpretation_notes.forEach(note => addText(notes, 'p', note)); notes.classList.remove('hidden'); } else { notes.classList.add('hidden'); } const results = $('#results'); results.replaceChildren(); const table = document.createElement('table'); const head = document.createElement('thead'); const headRow = document.createElement('tr'); data.columns.forEach(column => addText(headRow, 'th', column)); head.append(headRow); table.append(head); const body = document.createElement('tbody'); data.rows.forEach(row => { const rowElement = document.createElement('tr'); row.forEach(value => addText(rowElement, 'td', value)); body.append(rowElement); }); table.append(body); results.append(table);
}
async function ingest(formData) { status('Reading the full dataset and building its profile…'); const data = await request('/api/datasets/upload', { method: 'POST', body: formData }); datasetId = data.dataset_id; showProfile(data.profile); status('Dataset ready for review.'); }
async function analyze(payload) { try { status('Running safe local analysis…'); renderResult(await request(`/api/datasets/${encodeURIComponent(datasetId)}/analyze`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) })); status('Analysis complete.'); } catch (error) { status(error.message, true); } }

$('#chooseFile').addEventListener('click', () => $('#datasetFile').click());
$('#upload').addEventListener('submit', async event => { event.preventDefault(); try { await ingest(new FormData(event.target)); } catch (error) { status(error.message, true); } });
$('#datasetFile').addEventListener('change', async event => { if (!event.target.files.length) return; try { await ingest(new FormData($('#upload'))); } catch (error) { status(error.message, true); } });
$('#api').addEventListener('submit', async event => { event.preventDefault(); try { status('Importing public API data…'); const data = await request('/api/datasets/import-api', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ url: $('#apiUrl').value }) }); datasetId = data.dataset_id; showProfile(data.profile); status('API data ready for review.'); } catch (error) { status(error.message, true); } });
understandButton.addEventListener('click', async () => { try { status('Preparing a profile-based guide and starter questions…'); renderContext(await request(`/api/datasets/${encodeURIComponent(datasetId)}/understand`, { method: 'POST' })); status('Dataset guide is ready. Pick a question or write your own.'); } catch (error) { status(error.message, true); } });
$('#suggest').addEventListener('click', async () => { try { status('Gemini is preparing conservative suggestions from the profile, not raw rows…'); plan = await request(`/api/datasets/${encodeURIComponent(datasetId)}/suggest-cleanup`, { method: 'POST' }); renderPlan(plan); status('Review each proposed change before applying it.'); } catch (error) { status(error.message, true); } });
$('#stagePostgres').addEventListener('click', async () => { try { status('Copying an unchanged raw dataset to PostgreSQL staging…'); const receipt = await request(`/api/datasets/${encodeURIComponent(datasetId)}/stage-postgres`, { method: 'POST' }); status(`${receipt.rows_staged.toLocaleString()} raw records staged in PostgreSQL. ID: ${receipt.staging_dataset_id}`); } catch (error) { status(error.message, true); } });
$('#apply').addEventListener('click', async () => { try { const approvedIds = [...document.querySelectorAll('#suggestions input:checked')].map(input => input.value); const data = await request(`/api/datasets/${encodeURIComponent(datasetId)}/apply-plan`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ plan, approved_ids: approvedIds }) }); $('#validation').textContent = JSON.stringify(data.validation, null, 2); showProfile(data.profile); status('Selected changes applied and validated.'); } catch (error) { status(error.message, true); } });
$('#ask').addEventListener('click', () => analyze({ question: $('#question').value })); $('#runSql').addEventListener('click', () => analyze({ sql: $('#sql').value }));
