from operator import add
from typing import Annotated as ann
from typing import Literal

from pydantic import BaseModel, Field


class AgentState(BaseModel):
    messages: ann[list,add] = Field(default_factory=list, description="List of messages exchanged with the agent.")
    user_question: str = Field(default="", description="The original question asked by the user.")
    curated_ques: str = Field(default="", description="Curated question for the agent.")
    prompt_context: str = Field(default="", description="A detailed prompt with SQL DB context that will help agent to generate SQL query.")
    is_safe: Literal["Yes", "No"] = Field(default=False, description="Indicates whether the agent's response is safe.")
    generated_sql_query: str = Field(default="", description="The SQL query generated by the agent.")
    comments: str = Field(default="", description="Comments or reasoning behind the safety judgment on SQL Query.")
    sql_query_result: str = Field(default="", description="The result of executing the generated SQL query.")
    final_answer: str = Field(default="", description="The final answer provided by the agent after processing the SQL query result.")


class judgeSchema(BaseModel):
    answer: Literal["Yes", "No"] = Field(default=False, description="Indicates whether the agent's response is safe.")
    comments: str = Field(default="", description="Comments or reasoning behind the safety judgment on SQL Query.")



class ETLAgentSchema(BaseModel):
    messages: ann[list,add] = Field(default_factory=list, description="List of messages exchanged with the agent.")


class RouterSchema(BaseModel):   
    answer: Literal["sql", "etl"] = Field(default="", description="Indicates whether the agent's response is safe.")
    comments: str = Field(default="", description="Comments or reasoning behind the safety judgment on SQL Query.") 


class AIAgentSchema(BaseModel):
    messages: ann[list,add] = Field(default_factory=list, description="List of messages exchanged with the agent.")
    route_response: str = Field(default="", description="The final answer provided by the agent after processing the SQL query result.")


class DatasetWorkflowState(BaseModel):
    """Shared contract for the production workflow built on the original agents."""

    dataset_id: str = ""
    action: Literal["profile", "understand", "suggest_cleanup", "apply_cleanup", "analyze"]
    approved_ids: list[str] = Field(default_factory=list)
    question: str | None = None
    sql: str | None = None
